// <auto-generated />
using System;
using Confeccao.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Confeccao.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ConfeccaoDbContext))]
    [Migration("20260509050950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Confeccao.Domain.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("HasLining")
                        .HasColumnType("boolean")
                        .HasColumnName("has_lining");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("hex_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_colors");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_colors_name");

                    b.ToTable("colors", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("ButtonCount")
                        .HasColumnType("integer")
                        .HasColumnName("button_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_models_name");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.ModelStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_model_stages");

                    b.HasIndex("ModelId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_model_stages_model_id_sequence");

                    b.HasIndex("ModelId", "Stage")
                        .IsUnique()
                        .HasDatabaseName("ix_model_stages_model_id_stage");

                    b.ToTable("model_stages", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("CoveredButtonPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("covered_button_price");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<decimal?>("InterfacingExtra")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("interfacing_extra");

                    b.Property<decimal?>("LiningExtra")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("lining_extra");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<decimal?>("ReadyButtonPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("ready_button_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_prices");

                    b.HasIndex("UserId", "EffectiveFrom")
                        .HasDatabaseName("ix_prices_user_id_effective_from");

                    b.ToTable("prices", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.PriceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<int>("UpToQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("up_to_quantity");

                    b.HasKey("Id")
                        .HasName("pk_price_tiers");

                    b.HasIndex("PriceId")
                        .HasDatabaseName("ix_price_tiers_price_id");

                    b.ToTable("price_tiers", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.ModelStage", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.Model", "Model")
                        .WithMany("Stages")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_stages_models_model_id");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Price", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.PriceTier", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.Price", "Price")
                        .WithMany("Tiers")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_tiers_prices_price_id");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Model", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Price", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
