// <auto-generated />
using System;
using Confeccao.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Confeccao.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ConfeccaoDbContext))]
    [Migration("20260604031745_Financial")]
    partial class Financial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("laundry_package_number_seq");

            modelBuilder.HasSequence("order_number_seq");

            modelBuilder.HasSequence("payment_number_seq");

            modelBuilder.Entity("Confeccao.Domain.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("HasLining")
                        .HasColumnType("boolean")
                        .HasColumnName("has_lining");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("hex_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_colors");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_colors_name");

                    b.ToTable("colors", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Credit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Guid?>("PipelineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("size");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_credits");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_credits_model_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_credits_occurred_at");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_credits_order_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_credits_payment_id");

                    b.HasIndex("PipelineItemId")
                        .HasDatabaseName("ix_credits_pipeline_item_id");

                    b.HasIndex("UserId", "PaymentId")
                        .HasDatabaseName("ix_credits_user_id_payment_id");

                    b.ToTable("credits", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.LaundryPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_user_id");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("number")
                        .HasDefaultValueSql("nextval('laundry_package_number_seq')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Number"), "laundry_package_number_seq");

                    b.Property<DateTimeOffset>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_laundry_packages");

                    b.HasIndex("CompletedByUserId")
                        .HasDatabaseName("ix_laundry_packages_completed_by_user_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_laundry_packages_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_laundry_packages_status");

                    b.ToTable("laundry_packages", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.MiscCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_misc_costs");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_misc_costs_date");

                    b.ToTable("misc_costs", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("ButtonCount")
                        .HasColumnType("integer")
                        .HasColumnName("button_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_models_name");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.ModelStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_model_stages");

                    b.HasIndex("ModelId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_model_stages_model_id_sequence");

                    b.HasIndex("ModelId", "Stage")
                        .IsUnique()
                        .HasDatabaseName("ix_model_stages_model_id_stage");

                    b.ToTable("model_stages", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uuid")
                        .HasColumnName("color_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FabricCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fabric_code");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("instructions");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("number")
                        .HasDefaultValueSql("nextval('order_number_seq')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Number"), "order_number_seq");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ColorId")
                        .HasDatabaseName("ix_orders_color_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("planned_quantity");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_order_items_model_id");

                    b.HasIndex("OrderId", "ModelId", "Size")
                        .IsUnique()
                        .HasDatabaseName("ix_order_items_order_id_model_id_size");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("number")
                        .HasDefaultValueSql("nextval('payment_number_seq')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Number"), "payment_number_seq");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_number");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payments_user_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.PipelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("PipelineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_item_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_events");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_pipeline_events_event_type");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_pipeline_events_occurred_at");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_pipeline_events_order_id");

                    b.HasIndex("PipelineItemId")
                        .HasDatabaseName("ix_pipeline_events_pipeline_item_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_pipeline_events_user_id");

                    b.ToTable("pipeline_events", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.PipelineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uuid")
                        .HasColumnName("color_id");

                    b.Property<string>("ColorNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color_name_snapshot");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("FabricCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fabric_code_snapshot");

                    b.Property<Guid?>("LaundryPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("laundry_package_id");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<int>("QuantityDone")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_done");

                    b.Property<int>("QuantityTotal")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_total");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("size");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_items");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_pipeline_items_assigned_user_id");

                    b.HasIndex("LaundryPackageId")
                        .HasDatabaseName("ix_pipeline_items_laundry_package_id");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_pipeline_items_model_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_pipeline_items_order_id");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_pipeline_items_order_item_id");

                    b.HasIndex("Stage", "Status")
                        .HasDatabaseName("ix_pipeline_items_stage_status");

                    b.ToTable("pipeline_items", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("CoveredButtonPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("covered_button_price");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<decimal?>("InterfacingExtra")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("interfacing_extra");

                    b.Property<decimal?>("LiningExtra")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("lining_extra");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<decimal?>("ReadyButtonPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("ready_button_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_prices");

                    b.HasIndex("UserId", "EffectiveFrom")
                        .HasDatabaseName("ix_prices_user_id_effective_from");

                    b.ToTable("prices", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.PriceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<int>("UpToQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("up_to_quantity");

                    b.HasKey("Id")
                        .HasName("pk_price_tiers");

                    b.HasIndex("PriceId")
                        .HasDatabaseName("ix_price_tiers_price_id");

                    b.ToTable("price_tiers", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Credit", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credits_models_model_id");

                    b.HasOne("Confeccao.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credits_orders_order_id");

                    b.HasOne("Confeccao.Domain.Entities.Payment", "Payment")
                        .WithMany("Credits")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_credits_payments_payment_id");

                    b.HasOne("Confeccao.Domain.Entities.PipelineItem", "PipelineItem")
                        .WithMany()
                        .HasForeignKey("PipelineItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_credits_pipeline_items_pipeline_item_id");

                    b.HasOne("Confeccao.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credits_users_user_id");

                    b.Navigation("Model");

                    b.Navigation("Order");

                    b.Navigation("Payment");

                    b.Navigation("PipelineItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.LaundryPackage", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_laundry_packages_users_completed_by_user_id");

                    b.Navigation("CompletedByUser");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.ModelStage", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.Model", "Model")
                        .WithMany("Stages")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_stages_models_model_id");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Order", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_colors_color_id");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_models_model_id");

                    b.HasOne("Confeccao.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Model");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.PipelineEvent", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pipeline_events_orders_order_id");

                    b.HasOne("Confeccao.Domain.Entities.PipelineItem", "PipelineItem")
                        .WithMany()
                        .HasForeignKey("PipelineItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pipeline_events_pipeline_items_pipeline_item_id");

                    b.HasOne("Confeccao.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pipeline_events_users_user_id");

                    b.Navigation("Order");

                    b.Navigation("PipelineItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.PipelineItem", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pipeline_items_users_assigned_user_id");

                    b.HasOne("Confeccao.Domain.Entities.LaundryPackage", "LaundryPackage")
                        .WithMany()
                        .HasForeignKey("LaundryPackageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pipeline_items_laundry_packages_laundry_package_id");

                    b.HasOne("Confeccao.Domain.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_items_models_model_id");

                    b.HasOne("Confeccao.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_items_orders_order_id");

                    b.HasOne("Confeccao.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_items_order_items_order_item_id");

                    b.Navigation("AssignedUser");

                    b.Navigation("LaundryPackage");

                    b.Navigation("Model");

                    b.Navigation("Order");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Price", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.PriceTier", b =>
                {
                    b.HasOne("Confeccao.Domain.Entities.Price", "Price")
                        .WithMany("Tiers")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_tiers_prices_price_id");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Model", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Credits");
                });

            modelBuilder.Entity("Confeccao.Domain.Entities.Price", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
